src/OfflineMap.cpp

Here's a clean patch for the next-gen branch that will swap the order of lat & lon in the SCRIP format mapping file.  This will make tempestremap mapping files more closely follow the SCRIP convention.  
Tempestremap correctly labels the dimensions, so a good remapper should be able to work with both the Tempest order and the SCRIP order, but good remappers are few are far between

latlon order fix

---

src/GenerateOfflineMap.cpp

With this fix, mapping files produced by tempest remap, when using metadata produced by HOMME with the --in_meta option appear to be fully consistent with SCRIP format and can by applied by NCL codes which apply SCRIP format mapping files.

transpose the Jacobian data when reading in metadata

---

src/Makefile

Lapack and blas are needed by LinearRemapFV/SE0.
The -Wl,-rpath part puts the netcdf .so files into the shared lib path at
runtime.
Remove -framework, as that seems specific to Mac OS.
Do something different only if uname gives Linux; otherwise, do the same as
before.

Detect OS. If Linux, modify LDFLAGS.

---

config/ax_blas.m4

Let me know if this provides the right configurations on Yellowstone. If the MKL directory is part of LD_LIBRARY_PATH, it should pick things up. Tested on Blues/LCRC/ANL with Intel 15.0/MKL 11.2.
I did not test Intel+OSX. I don't have that combination available for testing locally.

Update the blas configuration to support Intel MKL when available

---

Makefile.gmake
README.md
src/Makefile.gmake
src/TempestRemapAPI.h

The older gmake based build system has been added back. Maintenance of both autoconf and gmake system should be pursued until the gmake system is deprecated eventually. 
To use the older system, execute:
`make -f Makefile.gmake clean`
`make -f Makefile.gmake`

Add the older build system to complement Autoconf

---

src/OfflineMap.h

These needed to be exposed so that forming an OfflineMap piecewise (especially in parallel sense) is possible. We are essentially using the Write functionality to serialize an OfflineMap that is computed on multiple processes, after reduction of all relevant data to the root process. In order to enable that, the `m_dSource*L*`/`m_dTarget*L*` variables need to be set correctly and consistently.

Getter methods for GetCenterLon/GetCenterLat/GetVertexLon/GetVertexLat

---

src/GridElements.cpp
src/GridElements.h

Very simple change to make sure we don't spew out a lot of output in parallel within the MBTR workflow.

Add verbosity flag for ConstructEdgeMap

---

config/ax_blas.m4

- Allow for better checks with Intel MKL versions for versions greater than 16.0
This change is essential to pick up the right MKL library combinations. The changes have been picked up from the MOAB ax_blas.m4 file and work cleanly. Tested on LCRC/Bebop and on MCS workstation.

Allow for better checks with Intel MKL 

---

src/DataArray1D.h
src/DataArray2D.h
src/DataArray3D.h

arrays were allocated in DataArray1D, 2D, 3D, using malloc but freed using delete []
This probably wouldn't cause any errors, but it causes problems with memory tracking tools

use free after using malloc

---

src/GridElements.cpp

with netcdf 4.6.3 (Darwin), and on the E3SM Compy machine, I'm getting errors converting to SCRIP format about setting _FillValue after data has been written to the array.  The ConvertExodusToScrip program aborts on errors, resulting in an incomplete scrip file.
with this patch, the code runs and generates a complete scrip file.  
Example showing error:
```
+ NE=4
+ atmgridnp4=TEMPEST_NE4.g
+ atmgrid=TEMPEST_NE4pg2.g
+ atmgrid_scrip=TEMPEST_NE4pg2.scrip.nc
+ /compyfs/software/tempestremap/intel/19.0.3/bin/GenerateCSMesh --alt --res 4 --out_format Netcdf4 --file TEMPEST_NE4.g
Parameters:
--res <integer> [4] 
--alt <bool> [true] 
--file <string> ["TEMPEST_NE4.g"] 
--out_format <string> ["Netcdf4"] 
=========================================================
..Generating mesh with resolution …
```

need to set _FillValue before writing any data

---

src/GridElements.cpp
src/GridElements.h

Make output less verbose when needed. Default is verbose=false in TempestRemap runs

Propagate verbose flag for coincident nodes check

---

src/OfflineMap.h

Make InitializeCoordinatesFromMeshFV and InitializeCoordinatesFromMeshFE routines protected so that derived classes can invoke them and compute center/vertex coordinates as needed.
This is used from the OnlineMap computation routines in MOAB when writing the file in h5m format.

Make some private routines to protected scope

---

src/GridElements.cpp

If num_elem attribute is unavailable, use the block element information to compute the total number of elements in the mesh by iterating over available elements/block data.

If num_elem attribute is missing, compute it

---

src/OfflineMap.cpp
src/OfflineMap.h

Take in the maximum number of nodes per element in the current mesh as an input if the user already knows this information. This is important when invoked in parallel (from MOAB) since at high-resolution, some processes could have say max of 5 `nve` and other processes could have 7 `nve` for a mixed MPAS grid. This leads to problems when writing out the CoordVertexLon/Lat variables as the offset is no longer constant (and map file is different in serial and parallel runs).
The updated API on protected method makes this recomputation simpler when doing I/O.

OfflineMap::InitializeCoordinatesFromMeshFV API update

---

src/GridElements.cpp

The padded vertex coordinates for polygonal meshes should keep same value as last vertex, and not 0.0.
ConvertExodusToSCRIP and ConvertSCRIPToExodus were not transpose operators. Now, this is fixed.
Additionally, made grid_imask as integer since this is what TR expects when reading back the SCRIP file.

Fixes for ConvertExodusToSCRIP/ConvertSCRIPToExodus

---

Makefile.am

Downstream codes like MOAB fails build otherwise due to missing header

Install CoordTransforms.h header

---

src/FiniteVolumeTools.cpp

Fix a potentially serious memory corruption bug for higher order FV-FV. 
The numerics for map generation does not get affected, but memory overflow on read may happen depending on the overlap grid.

Bugfix: Higher order FV-FV BuildIntegrationArray

---

src/netcdf.cpp
src/netcdfcpp.h

Expose public constructors in NetCDF C++ classes for NcVar/NcDim etc so that parallel extensions using derived classes in downstream packages (MOAB) can be implemented easily with minimal interface and code additions.
Note that to obtain parallelism with NetCDF v4+, we need NetCDF to be compiled with HDF5 and MPI.

Modifications to the NetCDF-C++ interfaces to allow NcFile extensions

---

src/GenerateOfflineMap.cpp
src/GenerateOfflineMapExe.cpp
src/LinearRemapSE0.cpp
src/LinearRemapSE0.h
src/TempestRemapAPI.h

dC is a matrix of size nCoeff x nCond, very sparse
for high number of intersection polygons, (~20k), this matrix dC size is about 200k x 20k, which is unreasonable
no need to use blas dgemv for that multiplication, all loops can be unrolled
change can be tested by commenting out 
#define DO_NOT_USE_DC_MATRIX

Remove usage of dC, which is too large 

---

src/FiniteVolumeTools.cpp
src/GridElements.cpp
src/GridElements.h
src/LinearRemapFV.cpp
src/LinearRemapSE0.cpp

Overlap polygons with at least 4 edges are decomposed in triangles from the center of mass.
do not decompose if overlap face is a triangle
Original decomposition uses lower number of triangles but this gives better shapes in general, and it does
not depend on the starting node of the polygon;
also, introduce a new function that computes area of a triangle from 3 nodes, by Gauss integration;
It simplifies the code more

center decomposition in triangles

---

src/GridElements.cpp

When using the jll binaries, we noticed that the `attrib1` was set to a strange result (`9.969209968386869e36` or `0x479e000000000000` in hex): according to the code however, it looks like it is supposed be `1.0`.
I think the problem is caused by this line: `&(dAttrib[0])` may not give a pointer to the array, but just a pointer to a location that has the same value as `dAttrib[0]` (I may be wrong: my C++ knowledge is pretty limited). From what I understand, I think the correct approach is to use [`.data()`](https://www.cplusplus.com/reference/vector/vector/data/).
cc: @jakebolewski (who knows more C++ than I do)

Use .data() to get pointer to std::vector

---

src/FiniteVolumeTools.cpp

use case:
`GenerateOfflineMap --in_mesh icotri15.g --out_mesh outCSMesh10.g --ov_mesh ov_fvcs.g --out_type cgll --out_np 2 --out_map vol.nc --volumetric`
this code crashes on master because some overlap faces are degenerate
On this branch, overlap faces with less than 3 edges are skipped; not sure why "volumetric" option triggers this behavior; so this PR fixes the symptom, but the cause of this is could be deeper.

skip degenerated triangles for volumetric option

---

Makefile.am
src/triangle.cpp

These changes are necessary to fix build on Windows
- switch `unsigned long` to `uintptr_t` in `triangle.cpp` (#109)
- Windows requires all symbols to be resolved, so BLAS and NetCDF libraries need to be linked against libTempestRemap
See https://github.com/JuliaPackaging/Yggdrasil/pull/5864

Windows fixes

---

src/Announce.cpp
src/CoarsenRectilinearData.cpp
src/Exception.h
src/GridElements.cpp
src/OfflineMap.cpp
src/OfflineMap.h
src/ShpToMesh.cpp

Fix several sprintf->snprintf and vsprintf->vsnprintf deprecation warnings when build the source repo on Mac OSX with clang 14+.

Caught by clang compiler on OSX

---

.github/workflows/conda_ubuntu_osx.yml
config/ax_blas.m4
config/ax_lapack.m4
configure.ac
mk/system.make
mk/system/perlmutter.make

Several configuration updates to build on Perlmutter with Intel compilers
- Autotools system update
- GNU makefile update with a new machine file

Updates to build cleanly on NERSC:Perlmutter
